Repository nmshd/documentation, pull requests merged in 2025-01, with the labels that each got.

#290 Add IdentityMetadata use cases
  _docs_integrate/data-model-overview.md
  _docs_integrate/error-codes.md
  _docs_integrate/terminate-relationships.md
  _docs_use-cases/use-case-consumption-delete-identitymetadata.md
  _docs_use-cases/use-case-consumption-get-identitymetadata.md
  _docs_use-cases/use-case-consumption-upsert-identitymetadata.md
  _docs_use-cases/use-case-transport-get-relationshiptemplate.md
  _includes/descr_id
Labels: enhancement

#291 Inconsistent choice of language in the footer
  _includes/footer.html
  index.md
Labels: bug

#292 Change contact eMail Address
  _includes/footer.html
Labels: bug

#294 Specify dbname prefix
  _docs_operate/configuration.md
Labels: bug

#293 Add scenario documentation for managing IdentityMetadata
  _data/navigation.yml
  _docs_integrate/data-model-overview.md
  _docs_integrate/manage-identitymetadata.md
  _docs_use-cases/use-case-consumption-upsert-identitymetadata.md
Labels: enhancement, wip

#295 Upgrade Dependencies
  Gemfile
  Gemfile.lock
Labels: dependencies

#296 Mention more Runtime validation
  Gemfile.lock
  _docs_integrate/01-integrate-scenarios.md
  _docs_integrate/create-attributes-for-yourself.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/error-codes.md
  _docs_operate/configuration.md
  _docs_use-cases/use-case-consumption-accept-incoming-request.md
  _docs_use-cases/use-case-consumption-check-if-incoming-request-can-be-accepted.md
  _docs_use-cases/use-case-consumption-create-a-repositoryattribute.md
  _docs_use-cases/use-case-consumption-create-outgoing-request.md
  _docs_use-cases/use-case-transport-create-own-relationshiptemplate.md
  _docs_use-cases/use-case-transport-create-relationship-with-relationshiptemplate.md
  _docs_use-cases/use-case-transport-send-message-to-recipients.md
Labels: enhancement

#298 Make `schemaURL` of SchematizedXML optional
  _docs_integrate/attribute-values.md
Labels: enhancement

#297 Add scenario for exchanging Files by using Attributes
  _data/navigation.yml
  _docs_explore/42-transport-layer.md
  _docs_integrate/attribute-values.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/exchange-files-using-attributes.md
  _docs_integrate/migration-from-v4-to-v5.md
  _docs_use-cases/use-case-transport-create-qr-code-for-file.md
  _docs_use-cases/use-case-transport-create-token-for-file.md
  _docs_use-cases/use-case-transport-create-token-qr-code-for-file.md
  _docs_use-cases/use-case-transport-download-file-of-attachment.md
  _docs_use-cases/use-case-transport-download-file.md
  _docs_use-cases/use-case-transport-get-file-metadata-of-attachment.md
  _docs_use-cases/use-case-transport-get-file-metadata.md
  _docs_use-cases/use-case-transport-get-or-load-file.md
  _docs_use-cases/use-case-transport-get-own-file.md
  _docs_use-cases/use-case-transport-load-file.md
  _docs_use-cases/use-case-transport-load-item-from-truncated-reference.md
  _docs_use-cases/use-case-transport-query-files.md
  _docs_use-cases/use-case-transport-query-metadata-of-files.md
  _docs_use-cases/use-case-transport-query-metadata-of-own-files.md
  _docs_use-cases/use-case-transport-query-metadata-of-peer-files.md
  _docs_use-cases/use-case-transport-upload-own-file.md
  _includes/descr_truncatedReference
Labels: enhancement, wip
