Repository nmshd/documentation, pull requests merged in 2025-03, with the labels that each got.

#303 Add error codes for Relationship creation
  _docs_integrate/error-codes.md
  _docs_integrate/establish-relationships.md
  _docs_integrate/requests-via-relationshiptemplates.md
  _docs_use-cases/use-case-transport-check-if-relationship-can-be-created.md
  _docs_use-cases/use-case-transport-create-relationship-with-relationshiptemplate.md
Labels: enhancement, wip

#304 Make `title` of AuthenticationRequestItem mandatory
  _docs_integrate/data-model-overview.md
  _docs_integrate/request-and-response-introduction.md
Labels: enhancement

#306 Update data model
  _docs_integrate/data-model-overview.md
Labels: enhancement

#308 Use `templateId` instead of `template` for Relationships
  _docs_integrate/establish-relationships.md
  _docs_integrate/integration-example.md
  _docs_integrate/requests-via-relationshiptemplates.md
  _docs_use-cases/use-case-transport-query-relationships.md
Labels: enhancement, wip

#299 Revision of scenarios for managing Attributes
  _docs_integrate/create-attributes-for-peer.md
  _docs_integrate/create-attributes-for-yourself.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/propose-attributes-to-peer.md
  _docs_integrate/read-attributes-from-peer.md
  _docs_integrate/share-attributes-with-peer.md
Labels: enhancement, wip

#310 Remove validity dates from Attributes
  _docs_integrate/create-attributes-for-yourself.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/exchange-files-using-attributes.md
  _docs_integrate/request-and-response-introduction.md
  _docs_use-cases/use-case-consumption-get-attributes.md
  _docs_use-cases/use-case-consumption-get-own-shared-attributes.md
  _docs_use-cases/use-case-consumption-get-peer-shared-attributes.md
  _docs_use-cases/use-case-consumption-succeed-a-relationshipattribute-and-notify-peer.md
  assets/js/iql-demo.js
Labels: refactoring

#311 Add `tags` to File
  _docs_integrate/data-model-overview.md
  _docs_use-cases/use-case-transport-query-metadata-of-files.md
  _docs_use-cases/use-case-transport-query-metadata-of-own-files.md
  _docs_use-cases/use-case-transport-query-metadata-of-peer-files.md
  _docs_use-cases/use-case-transport-upload-own-file.md
Labels: enhancement

#313 Standardized capitalization of terms
  README.md
  _docs_explore/01-how_does_enmeshed_work.md
  _docs_explore/06-features.md
  _docs_explore/22-security.md
  _docs_explore/23-privacy.md
  _docs_explore/41-backbone-layer.md
  _docs_explore/42-transport-layer.md
  _docs_explore/50-app.md
  _docs_explore/51-backbone.md
  _docs_explore/60-addresses.md
  _docs_integrate/02-connector-create-relationships.md
  _docs_integrate/diagrams/Connector_API_!Template.pu
  _docs_integrate/diagrams/Connector_API_AcceptRelationshipRequest.pu
  _docs_integrate/diagrams/Connector_API_CreateRelationshipRequest.pu
  _docs_integrate/diagrams/Connector_API_CreateTemplate.pu
  _docs_integrate/diagrams/Connector_API_GetMessage.pu
  _docs_integrate/diagrams/Connector_API_GetOpenRelationshipRequests.pu
  _docs_integrate/diagrams/Connector_API_GetTemplate.pu
  _docs_integrate/diagrams/Connector_API_PreRelationshipOverview.pu
  _docs_integrate/diagrams/Connector_API_ReceiveMessage.pu
  _docs_integrate/diagrams/Connector_API_ReceiveRelationshipRequest.pu
  _docs_integrate/diagrams/Connector_API_SendMessage.pu
  _docs_integrate/diagrams/Connector_Flow_CreateAuthToken.pu
  _docs_integrate/diagrams/Connector_Flow_UpgradeProfile.pu
  _docs_integrate/error-codes.md
  _docs_integrate/examples/docker-compose-with-existing-mongodb.yml
  _docs_integrate/examples/docker-compose-with-ferretdb.yml
  _docs_integrate/examples/docker-compose-with-mongodb.yml
  _docs_operate/overview-of-connector-operations.md
  _docs_operate/security-considerations.md
  _docs_operate/troubleshooting-guide.md
  _docs_operate/use-the-backbone-admin-ui.md
  _docs_use-cases/use-case-device-get-appruntime-health-status.md
  _docs_use-cases/use-case-device-get-appruntime-version-information.md
  _docs_use-cases/use-case-human-device_-external-usecase.md
  _docs_use-cases/use-case-human-scan_-qr-code-on-different-device.md
  _docs_use-cases/use-case-user_interface-get-app-version-information.md
  _docs_use-cases/use-case-user_interface-refresh-screen-screen.md
  _docs_use-cases/use-case-user_interface-show-screen-screen.md
  _docs_use-cases/use-case-user_interface-start-app-with-parameters-by-using-link.md
  _docs_use-cases/use-case-user_interface-start-app-without-parameters.md
  _docs_use/03-use-scenarios.md
  _docs_use/install-the-app.md
  _docs_use/register-a-new-online-account-with-an-organization.md
  _docs_use/upgrade-an-existing-online-account-at-an-organization.md
  _posts/2022-10-06-road-to-enmeshed-v2.md
Labels: chore
