Repository nmshd/documentation, pull requests merged in 2025-05, with the labels that each got.

#324 Add docs for the authentication of the webhooks module
  _docs_operate/configuration.md
Labels: enhancement

#326 Broken links due to capitalization
  _docs_explore/61-runtime.md
  _docs_integrate/connector-events.md
  _docs_use-cases/use-case-consumption-create-and-complete-outgoing-request-from-relationshiptemplate-response.md
  _docs_use-cases/use-case-consumption-get-attribute.md
  _docs_use-cases/use-case-consumption-get-own-shared-attributes.md
  _docs_use-cases/use-case-consumption-get-peer-shared-attributes.md
Labels: bug

#327 Add error codes
  _docs_integrate/error-codes.md
Labels: enhancement

#328 Typing errors and other minor mistakes
  _docs_integrate/attribute-values.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/event-introduction.md
  _docs_operate/security-considerations.md
  _docs_use-cases/use-case-consumption-execute-a-relationshipattributequery.md
  _includes/descr_expiresAt
  _pages/contribute.md
Labels: bug

#329 Add description of AttributeTagCollection
  _docs_integrate/data-model-overview.md
  _docs_use-cases/use-case-consumption-get-attributetagcollection.md
Labels: enhancement

#330 Update max length of FileReferences
  _docs_integrate/attribute-values.md
Labels: chore

#335 Add `wrongRelationshipStatusToSetDeletionInfo` error code
  _docs_integrate/error-codes.md
Labels: enhancement

#331 Add validation for IdentityAttribute `tags`
  _docs_integrate/attribute-introduction.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/error-codes.md
  _docs_integrate/exchange-files-using-attributes.md
  _docs_use-cases/use-case-transport-upload-own-file.md
Labels: enhancement

#334 Remove deprecated use cases
  _docs_use-cases/use-case-consumption-delete-a-third-party-owned-relationshipattribute-and-notify-peer.md
  _docs_use-cases/use-case-consumption-delete-a-thirdpartyrelationshipattribute-and-notify-peer.md
  _docs_use-cases/use-case-transport-load-item-from-reference.md
  _docs_use-cases/use-case-transport-load-item-from-truncated-reference.md
Labels: chore

#336 Remove deprecated publisher modules
  _docs_operate/configuration.md
  _docs_operate/modules.md
Labels: chore

#337 Add check if RepositoryAttribute can be created use case
  _docs_use-cases/use-case-consumption-check-if-repositoryattribute-can-be-created.md
  _docs_use-cases/use-case-consumption-create-a-repositoryattribute.md
  _docs_use-cases/use-case-transport-check-if-relationship-can-be-created.md
Labels: enhancement

#338 Mention validation of IdentityAttribute `tags` in use cases
  _docs_use-cases/use-case-consumption-check-if-repositoryattribute-can-be-created.md
  _docs_use-cases/use-case-consumption-create-a-repositoryattribute.md
  _docs_use-cases/use-case-transport-upload-own-file.md
Labels: enhancement

#325 Add migration guide for v7
  _data/navigation.yml
  _docs_integrate/01-integrate-scenarios.md
  _docs_integrate/migration-from-v6-to-v7.md
Labels: enhancement

#340 Mention removed `GET /api/v2/Attributes/Valid` Connector route
  _docs_integrate/migration-from-v6-to-v7.md
Labels: enhancement

#341 Mention optional File `title` in v7 migration guide
  _docs_integrate/migration-from-v6-to-v7.md
Labels: enhancement

#344 Add RelationshipTemplateAllocationsExhausted event
  _docs_integrate/connector-events.md
Labels: enhancement

#343 Mention validation of Mail recipients
  _docs_integrate/data-model-overview.md
Labels: enhancement

#342 Add `reference` to objects
  _docs_explore/42-transport-layer.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/diagrams/Connector_API_GetTemplate.pu
  _docs_integrate/error-codes.md
  _docs_integrate/establish-relationships.md
  _docs_integrate/exchange-files-using-attributes.md
  _docs_integrate/requests-via-relationshiptemplates.md
  _docs_use-cases/use-case-anonymous-load-token-by-truncated-reference-without-having-an-account.md
  _docs_use-cases/use-case-transport-get-file-metadata.md
  _docs_use-cases/use-case-transport-load-file.md
  _docs_use-cases/use-case-transport-load-relationshiptemplate-created-by-others.md
  _docs_use-cases/use-case-transport-load-token-created-by-others.md
  _docs_use-cases/use-case-transport-upload-own-file.md
  _includes/descr_reference
  _includes/descr_truncatedReference
Labels: enhancement

#346 Add `isOwn` property to Token
  _docs_explore/42-transport-layer.md
  _docs_integrate/data-model-overview.md
  _docs_use-cases/use-case-transport-query-tokens-by-parameters.md
Labels: enhancement

#345 Remove deprecated `truncatedReference` property of objects
  _docs_explore/42-transport-layer.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/migration-from-v6-to-v7.md
  _docs_use-cases/use-case-anonymous-load-token-by-reference-without-having-an-account.md
Labels: enhancement, wip

#347 Add wasAutomaticallyDecided to LocalRequest
  _docs_integrate/data-model-overview.md
Labels: enhancement

#348 Uniqueness of IdentityAttribute and File `tags` and Message `recipients` and Message `attachments`
  _docs_integrate/data-model-overview.md
Labels: enhancement
