Repository nmshd/documentation, pull requests merged in 2025-04, with the labels that each got.

#314 Use consistent formatting in data model overview
  _docs_integrate/data-model-overview.md
Labels: refactoring

#316 Add commas
  _docs_integrate/data-model-overview.md
  _docs_integrate/request-and-response-introduction.md
Labels: refactoring

#317 Add `linkDisplayText` to Consents
  _docs_integrate/attribute-values.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/request-and-response-introduction.md
  _docs_integrate/request-one-time-consent-of-peer.md
  _docs_integrate/request-persistent-consent-of-peer.md
Labels: enhancement

#319 Bump Dependencies
  Gemfile.lock
Labels: dependencies

#321 Fix formatting
  _docs_use-cases/use-case-transport-check-if-relationship-can-be-created.md
Labels: chore

#318 Documentation for FormFieldRequestItem
  _data/navigation.yml
  _docs_integrate/create-attributes-for-peer.md
  _docs_integrate/data-model-overview.md
  _docs_integrate/form-fields-within-requests.md
  _docs_integrate/propose-attributes-to-peer.md
  _docs_integrate/read-attributes-from-peer.md
  _docs_integrate/request-and-response-introduction.md
  _docs_integrate/request-one-time-consent-of-peer.md
  _docs_integrate/request-persistent-consent-of-peer.md
  _docs_integrate/share-attributes-with-peer.md
Labels: enhancement

#322 Move QR code use cases from Runtime to Connector
  _docs_integrate/error-codes.md
  _docs_use-cases/use-case-device-create-qr-code-for-file.md
  _docs_use-cases/use-case-device-create-qr-code-for-own-relationshiptemplate.md
  _docs_use-cases/use-case-device-create-token-qr-code-for-file.md
  _docs_use-cases/use-case-device-create-token-qr-code-for-own-relationshiptemplate.md
  _docs_use-cases/use-case-device-get-qr-code-for-single-token.md
Labels: chore

#323 Document the removal of the FreeTextRequestItem and the RequestItem title
  _docs_integrate/data-model-overview.md
  _docs_integrate/request-and-response-introduction.md
Labels: enhancement
